# Drop-in configuration for applyupdates script
# Disabled by default. Enable by setting enabled = true

[applyupdates]
command = /opt/terminusd/scripts/example-package-updates.sh
priority = 1000
critical = true
user = root
group = wheel
env = /etc/inhibitor-env.d/applyupdates.env
enabled = false
