# Drop-in configuration for terminate user sessions script
# Disabled by default. Enable by setting enabled = true

[terminateusersessions]
command = /usr/libexec/terminusd/examples/example-terminate-user-sessions.sh
priority = 200
user = root
group = root
enabled = false